### ISSUE TITLE
Specify dependencies in package.json?

### ISSUE THREAD

**Issue by thomasnordlund** [thaiat/generator-angular-famous-ionic#113]
Is there a reason why dependencies/devDependencies are not specified in package.json? I'm having to manually install all of the node modules.

**Comment by thaiat** [comment]
can you give more details about what's happening for you.
Normally this generator calls a sub generator (generator-sublime) that will npm install all the needed dependencies in package.json

This is because you can't have 2 generators changing the same file.

Anyway you should not have to install things manually.
I m guessing you got an error in the generator. One pre requisite (i will have to add that to the doc) is to upgrade your version of npm 
```
npm install -g npm
```

Former versions have a nasty race condition bug that may explain you issue.

**Comment by thomasnordlund** [comment]
I upgraded my version of npm. Ran the generator again and got this error:

'`darwin-x64-v8-3.14` exists; testing
-

․․․․․․․․․․․․․․․․․\

  26 passing (66ms)

Binary is fine; exiting
npm ERR! cb() never called!

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at emit (events.js:74:15)
    at done (/Users/thomasnordlund/.nvm/v0.10.35/lib/node_modules/generator-sublime/node_modules/yeoman-generator/lib/base.js:383:23)
    at null.<anonymous> (/Users/thomasnordlund/.nvm/v0.10.35/lib/node_modules/generator-sublime/node_modules/yeoman-generator/lib/actions/install.js:44:7)
    at ChildProcess.emit (events.js:117:20)
    at Process.ChildProcess._handle.onexit (child_process.js:810:12)'

**Comment by thomasnordlund** [comment]
Upgraded my version of npm. Ran the generator again and got this error:

`darwin-x64-v8-3.14` exists; testing
-

․․․․․․․․․․․․․․․․․\

  26 passing (66ms)

Binary is fine; exiting
npm ERR! cb() never called!

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at emit (events.js:74:15)
    at done (/Users/thomasnordlund/.nvm/v0.10.35/lib/node_modules/generator-sublime/node_modules/yeoman-generator/lib/base.js:383:23)
    at null.<anonymous> (/Users/thomasnordlund/.nvm/v0.10.35/lib/node_modules/generator-sublime/node_modules/yeoman-generator/lib/actions/install.js:44:7)
    at ChildProcess.emit (events.js:117:20)
    at Process.ChildProcess._handle.onexit (child_process.js:810:12)

**Comment by thaiat** [comment]
what is your version if npm ? what s your os?

try doing the following:
npm uninstall -g generator-angular-famous-ionic
npm uninstall -g generator-sublime
npm cache clear

then reinstall and re run the generator

**Comment by thomasnordlund** [comment]
npm: 2.3.0
os: OSX 10.9.5

**Comment by thaiat** [comment]
cool, i deserve a star no ?
