### ISSUE TITLE
has no method 'slugify'

### ISSUE THREAD

**Issue by mydearxym** [thaiat/generator-angular-famous-ionic#118]
drive me crazy ...
when i run :  yo angular-famous-ionic hello
i get this: 
```javascript
/usr/local/lib/node_modules/generator-sublime/app/index.js:59
        this.appnameFolder = _.slugify(this.appname);
                               ^
TypeError: Object function lodash(value) {
      // don't wrap if already wrapped, even if wrapped by a different `lodash` constructor
      return (value && typeof value == 'object' && !isArray(value) && hasOwnProperty.call(value, '__wrapped__'))
       ? value
       : new lodashWrapper(value);
    } has no method 'slugify'
    at new Class.extend.constructor (/usr/local/lib/node_modules/generator-sublime/app/index.js:59:32)
    at Environment.instantiate (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:281:10)
    at Environment.create (/usr/local/lib/node_modules/yo/node
```

**Comment by thaiat** [comment]
hi @mydearxym ,
try not using the hello argument when running the generator
just:
- mkdir hello
- cd hello
- yo angular-famous-ionic

it should unblock you

**Comment by mydearxym** [comment]
still get this ...
my env is 
```javascript
node --version  => v0.10.24
npm  --version  => 2.1.3
```

```javascript
python is installed, continuing...


     _-----_
    |       |    .--------------------------.
    |--(o)--|    |  Welcome to the amazing  |
   `---------´   |   angular-famous-ionic   |
    ( _´U`_ )    |        generator!        |
    /___A___\    '--------------------------'
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 


/usr/local/lib/node_modules/generator-sublime/app/index.js:59
        this.appnameFolder = _.slugify(this.appname);
                               ^
TypeError: Object function lodash(value) {
      // don't wrap if already wrapped, even if wrapped by a different `lodash` constructor
      return (value && typeof value == 'object' && !isArray(value) && hasOwnProperty.call(value, '__wrapped__'))
       ? value
       : new lodashWrapper(value);
    } has no method 'slugify'
    at new Class.extend.constructor (/usr/local/lib/node_modules/generator-sublime/app/index.js:59:32)
    at Environment.instantiate (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:281:10)
    at Environment.create (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:258:15)
    at composeWith (/usr/local/lib/node_modules/generator-angular-famous-ionic/node_modules/yeoman-generator/lib/base.js:564:26)
    at Class.extend.prompting.welcome (/usr/local/lib/node_modules/generator-angular-famous-ionic/app/index.js:56:18)
    at /usr/local/lib/node_modules/generator-angular-famous-ionic/node_modules/yeoman-generator/lib/base.js:395:14
    at processImmediate [as _immediateCallback] (timers.js:330:15)
```

**Comment by thaiat** [comment]
@mydearxym are u available for a skype / google hangout ?

**Comment by mydearxym** [comment]
@thaiat it's my fault ...  i reinstall the `generator-sublime` package and everything works fine, i guess it's the version match problem..  thanks ~
